Метрики
Byndyusoft/Byndyusoft.Execution.Metrics pull request #1
Opened 2023-10-03 08:06 UTC by Mblkolo

Добавлена реализация метрик для входящих http запросов и hangfire.

2023-10-03 10:59 UTC, Alex-Grigorichev requested changes

2023-10-03 10:59 UTC, Alex-Grigorichev commented on src/Byndyusoft.Execution.Metrics.AspNet/AspNetCoreDiagnosticObserver.cs
> +        if (activity == null)
is null?

2023-10-03 10:59 UTC, Alex-Grigorichev commented on src/Byndyusoft.Execution.Metrics.AspNet/AspNetDurationMetricsInstrumentation.cs
> +public class AspNetDurationMetricsInstrumentation :IDisposable
пробела не хватает

2023-10-03 10:59 UTC, Alex-Grigorichev commented on src/Byndyusoft.Execution.Metrics.Hangfire/HangfireConfigurationExtensions.cs
> +    /// <param name="configuration"></param>
заполнить либо удалить

2023-10-03 10:59 UTC, Alex-Grigorichev commented on src/Byndyusoft.Execution.Metrics.Hangfire/HangfireExecutionMetricDurationFilter.cs
> +        filterContext.Items.Add("handler", handler);
вынести константу "handler"

2023-10-03 10:59 UTC, Alex-Grigorichev commented on src/Byndyusoft.Execution.Metrics/Byndyusoft.Execution.Metrics.csproj
> +	<PropertyGroup>
добавить паблиш пакета в нюгет (в актуальном шаблоне кубика это есть) во всех пакетах 
также добавить публикацию лицензии

2023-10-03 10:59 UTC, Alex-Grigorichev commented on tests/ExampleTestsProject/ExampleClassTests.cs
> +            Assert.That(true, Is.True);
будут тесты на пакеты?

2023-10-03 10:59 UTC, Alex-Grigorichev commented on src/Byndyusoft.Execution.Metrics/ExecutionHandler.cs
> +
лишняя пустая строка

2023-10-03 10:59 UTC, Alex-Grigorichev commented on src/Byndyusoft.Execution.Metrics.AspNet/AspNetDurationMetricsInstrumentation.cs
> +public class AspNetDurationMetricsInstrumentation :IDisposable
и документации

2023-10-03 10:59 UTC, Alex-Grigorichev commented on src/Byndyusoft.Execution.Metrics/ExecutionDurationMeter.cs
> +                                  new("status_code", statusCode switch {
а почему статус код либо OK либо ERROR? судя по названию тут какое-то число должно быть...

2023-10-03 10:59 UTC, Alex-Grigorichev commented on src/Byndyusoft.Execution.Metrics/Byndyusoft.Execution.Metrics.csproj
> +		<PackageReference Include="OpenTelemetry" Version="1.3.1" />
использовать самую актуальную версию

2023-10-03 14:09 UTC, Mblkolo commented on src/Byndyusoft.Execution.Metrics/ExecutionDurationMeter.cs
> +                                  new("status_code", statusCode switch {
Так в спецификации опентрейсинга

2023-10-03 14:10 UTC, Mblkolo commented on tests/ExampleTestsProject/ExampleClassTests.cs
> +            Assert.That(true, Is.True);
Сейчас нет

2023-10-03 14:11 UTC, Mblkolo commented on src/Byndyusoft.Execution.Metrics/Byndyusoft.Execution.Metrics.csproj
> +	<PropertyGroup>
Использовал шаблон кубика, пререлизный пакет запаблишился отлично.

2023-10-04 04:35 UTC, Alex-Grigorichev commented on src/Byndyusoft.Execution.Metrics/Byndyusoft.Execution.Metrics.csproj
> +	<PropertyGroup>
В шаблоне кубика был косяк, я его вчера при ревью заметил и поправил.
Вот так README должен выглядеть, если добавить тег в csproj https://www.nuget.org/packages/Byndyusoft.ModelResult#readme-body-tab
Вот так выглядит README кубика сейчас https://www.nuget.org/packages/Byndyusoft.Byndyusoft.Execution.Metrics.Hangfire/0.0.1-tags-v0.0.1-prelease#readme-body-tab

2023-10-04 04:57 UTC, Alex-Grigorichev commented on tests/ExampleTestsProject/ExampleClassTests.cs
> +            Assert.That(true, Is.True);
А когда будут?

2023-10-04 09:44 UTC, Alex-Grigorichev commented on src/Byndyusoft.Execution.Metrics.Hangfire/HangfireConfigurationExtensions.cs
> +﻿using Byndyusoft.Execution.Metrics.Hangfire;
Давай ещё по папкам разобьём файлы

2023-10-05 05:17 UTC, Mblkolo commented on src/Byndyusoft.Execution.Metrics.AspNet/AspNetCoreDiagnosticObserver.cs
> +        if (activity == null)
Не буду менять, считаю вкусовщиной.

2023-10-05 05:18 UTC, Mblkolo commented on src/Byndyusoft.Execution.Metrics.AspNet/AspNetDurationMetricsInstrumentation.cs
> +public class AspNetDurationMetricsInstrumentation :IDisposable
++

2023-10-05 05:19 UTC, Mblkolo commented on src/Byndyusoft.Execution.Metrics.Hangfire/HangfireConfigurationExtensions.cs
> +    /// <param name="configuration"></param>
++

2023-10-05 05:20 UTC, Mblkolo commented on src/Byndyusoft.Execution.Metrics.Hangfire/HangfireExecutionMetricDurationFilter.cs
> +        filterContext.Items.Add("handler", handler);
++

2023-10-05 06:01 UTC, Mblkolo commented on src/Byndyusoft.Execution.Metrics/Byndyusoft.Execution.Metrics.csproj
> +	<PropertyGroup>
++

2023-10-05 06:02 UTC, Mblkolo commented on tests/ExampleTestsProject/ExampleClassTests.cs
> +            Assert.That(true, Is.True);
Когда появится что тестить

2023-10-05 06:02 UTC, Mblkolo commented on src/Byndyusoft.Execution.Metrics/ExecutionHandler.cs
> +
++

2023-10-05 06:03 UTC, Mblkolo commented on src/Byndyusoft.Execution.Metrics/Byndyusoft.Execution.Metrics.csproj
> +		<PackageReference Include="OpenTelemetry" Version="1.3.1" />
++

2023-10-05 06:04 UTC, Mblkolo commented on src/Byndyusoft.Execution.Metrics.Hangfire/HangfireConfigurationExtensions.cs
> +﻿using Byndyusoft.Execution.Metrics.Hangfire;
А зачем? их тут всего 2

2023-10-05 06:32 UTC, Alex-Grigorichev commented on src/Byndyusoft.Execution.Metrics/Byndyusoft.Execution.Metrics.csproj
> +		<PackageReference Include="OpenTelemetry" Version="1.3.1" />
как же в гитхабе не удобно смотреть ПРы...

2023-10-05 06:34 UTC, Alex-Grigorichev commented on src/Byndyusoft.Execution.Metrics/Byndyusoft.Execution.Metrics.csproj
> +	<PropertyGroup>
Удалил лицензии в шаблоне из проекта, резолвю конверсэйшен

2023-10-05 06:42 UTC, Alex-Grigorichev commented on README.md
> +.AddOpenTelemetryMetrics(builder =>
OpenTelemetry в актуальных версиях немного поменяли добавление OpenTelemetry, теперь она выглядит как-то так:
`.AddOpenTelemetry()
            .WithTracing
                (builder =>
                     {
                         builder
                             .AddAspNetCoreInstrumentation()
                             .AddHttpClientInstrumentation()
                             .AddOtlpExporter(configureOtlp);
                     })
            .WithMetrics(builder =>
                             {
                                 builder.AddPrometheusExporter()
                                        .AddRuntimeInstrumentation()
                                        .AddAspNetCoreInstrumentation()
                                        .AddHttpClientInstrumentation();
                             });`
Давай поменяем этот момент в документации, чтобы она была актуальной для новых версий

2023-10-05 07:54 UTC, Alex-Grigorichev approved these changes
Апрув, но хотелось бы ещё получить ревью README от кого-то, кто не погружен в OpenTelemetry, чтобы понять, насколько будет понятно

2023-10-05 09:48 UTC, merged